### ISSUE TITLE
[Booking][mobile] Nombre de places "vide" lors de l'inscription à un créneau

### ISSUE THREAD

**Issue by guilbill** [lgangloff/crossfit#1]
Sur la version mobile :
- Je me connecte,
- Je vais sur "Planning",
- Je sélectionne un créneau libre,
- J'obtiens la modale suivante :

![planning](https://cloud.githubusercontent.com/assets/560852/10876806/6350b642-8140-11e5-8daf-c8edafd16b63.png)

**Comment by guillaumecolin** [comment]
Corrigé : https://github.com/lgangloff/crossfit/commit/15c1980c515d7a5fbd0c16af3523cbe2edc5e022
