### ISSUE TITLE
[admin][timeslot] Impossible de gérer les jours spéciaux

### ISSUE THREAD

**Issue by guillaumecolin** [lgangloff/crossfit#10]
Pour un jour férié (11 novembre) je ne peux pas créer un wod juste pour ce jour (12h30)

**Comment by lgangloff** [comment]
L'entité TimeSlot va évoluer.
Un TimeSlot, c'est un créneau. Aujourd'hui, les créneaux n'étaient configurables que pour être répétés toutes les semaines (dayOfWeek). 
Un 2e attribut va être ajouté (date). Il indiquera que ce créneau n'est valable qu'à cette date.
