### ISSUE TITLE
[admin][member] Afficher le nombre de membres

### ISSUE THREAD

**Issue by guillaumecolin** [lgangloff/crossfit#14]
Il n'y a aucune information sur le nombre de membres enregistrés

**Comment by lgangloff** [comment]
Enregistré/inscrits pour un wod ?

**Comment by guillaumecolin** [comment]
Enregistré en base

**Comment by lgangloff** [comment]
Corrigé, le titre de la page est de la forme: Gestion des 40/71 adhérents.
Le premier nombre est le nombre d'éléments affiché dans la liste (evolue en fonction du scroll)
Le deuxieme est le nombre total d'éléments en base.
