### ISSUE TITLE
[CSS][mobile] les drop down des menus ne fonctionnent pas

### ISSUE THREAD

**Issue by guilbill** [lgangloff/crossfit#2]
Sur la version mobile :
- Je meconnecte,
- Je clic sur ![image](https://cloud.githubusercontent.com/assets/560852/10876856/f17c427e-8140-11e5-8945-64fdd4f73ed5.png),
- Les drop down ne se déplient lorsque l'on clique dessus.
  ![image](https://cloud.githubusercontent.com/assets/560852/10876867/15c137fc-8141-11e5-9e52-0e34ec900510.png)

**Comment by guillaumecolin** [comment]
Corrigé : https://github.com/lgangloff/crossfit/commit/2675fd9bf8e5d74c8dab74a5b24641b5fd09fa1c
